USE DbSeries;

ALTER TABLE [ClassificacaoEtaria]
ADD CodExterno VARCHAR(12);

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdDiretor];   
ALTER TABLE Diretor  
DROP CONSTRAINT PK_DIRETOR;  
ALTER TABLE Diretor ADD PRIMARY KEY (IdDiretor)

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdProdutora];    
ALTER TABLE Produtora  
DROP CONSTRAINT PK_PRODUTORA;   
ALTER TABLE Produtora ADD PRIMARY KEY (IdProdutora)

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdPaisOrigem];    
ALTER TABLE PaisOrigem  
DROP CONSTRAINT [PK_PAISORIGEM];   
ALTER TABLE PaisOrigem ADD PRIMARY KEY (IdPais)

ALTER TABLE Serie
DROP COLUMN [IdDiretor];
ALTER TABLE Serie
DROP COLUMN [IdProdutora];
ALTER TABLE Serie
DROP COLUMN [IdPaisOrigem];
ALTER TABLE Serie
ADD Criadores VARCHAR(200);
ALTER TABLE Serie
ADD IdGenero INT;